### ISSUE TITLE
[FEATURE] How to install Add-On Proxy on Mac

### ISSUE THREAD

**Issue by RobertSmith8** [diegomanuel/binance-to-google-sheets#143]
Thx a lot for the Binance to Google Sheets Add-On Proxy

I have installed Erlang and Elixir using Homebrew on mac

But I was not able to run **make setup**

Can u pls add a Installation guide for the proxy server implementation in Elixir on mac

**Comment by diegomanuel** [comment]
Hey @RobertSmith8, mac and unix/linux are pretty similar so all the described steps in the readme should work, except the 1st one that installs OS packages using `apt` instead of `brew`.
But, as you didn't use `asdf` to install Erlang/Elixir, then you need to remove this line from `make setup` target:
```
CPP=cpp EGREP=egrep KERL_CONFIGURE_OPTIONS="--without-javac --without-wx" asdf install
```
Plz note that by using `brew` you probably didn't choose what versions of Erlang and Elixir to install, although it should work anyways with any of the newest versions that surelly `brew` installed.
I still recommend to use `asdf`, that will install the exact versions defined at `.tool-versions` file.

All the other `Makefile` targets should work fine on mac as well.
Good luck! :beers:

**PS:** I recommend to setup a basic/small instance at GCP or AWS (like AWS Lightsail with Ubuntu 20+) in any location you like, login through SSH, run all the steps in the readme and open `4000-4005` TCP ports.
