### ISSUE TITLE
[ERROR] Wallet Fetching throws Error 404

### ISSUE THREAD

**Issue by HexHyte** [diegomanuel/binance-to-google-sheets#146]
I am getting the following error every time i try to use this command:

**=BINANCE("account","spot")**
_results in_
Error: Request failed with status: 404

---

The same error appears when trying to Enable or Disable any Wallet type from the top bar menu:
![image](https://user-images.githubusercontent.com/37019481/212870478-beaa2283-da93-4ab3-aefe-40e48b0718e3.png)

---

I also discovered i cannot change Update Interval for Account Info, it always stay at 1m no matter what i choose:
![image](https://user-images.githubusercontent.com/37019481/212875201-43516adc-5aff-4894-805b-2d2978903def.png)

---

The error started to appear after updating the script from 0.5.1 to 0.5.3 but now the error still shows up even when reverting the script back to 0.5.1.

**Comment by war3game** [comment]
Same error here

**Comment by diegomanuel** [comment]
Hey folks, it's currently working fine for me. The `404` error shouldn't happen if you didn't change anything at `config.gs`.

> I also discovered i cannot change Update Interval for Account Info, it always stay at 1m no matter what i choose:

That only happens when you have an error (like the `404` you mention) and the script automatically re-enqueue the request to retry it in the next minute (and that's why you see the "1m" selected) but it should be back to the value you've set once the request works fine again.

I'm closing this issue since there is no error in the code itself.

**Comment by HexHyte** [comment]
> The `404` error shouldn't happen if you didn't change anything at `config.gs` (nor in any other code file).

The only edit that i've made was the one following this issue (error451): 
https://github.com/diegomanuel/binance-to-google-sheets/issues/142#issue-1469519833

With the proposed solution i can at least fetch the Prices (using= BINANCE("prices","","") but with the Wallet i get the mentioned 404 error.

**Comment by diegomanuel** [comment]
That's because the proposed solution there only works for prices data (as it says there).
You won't be able to fetch your wallet data.
The only option that I could recomment is the proxy-one: https://github.com/diegomanuel/binance-to-google-sheets/issues/142#issuecomment-1345361826

Good luck.
