### ISSUE TITLE
Connecting multiple binance accounts

### ISSUE THREAD

**Issue by gabrieljaegerde** [diegomanuel/binance-to-google-sheets#15]
I am using multiple trading bots on different binance accounts and wanted to get them all integrated into the dashboard. I made amendments to you code to allow for that. Are you working on this already? Otherwise, I am happy to create a pull request.

**Comment by diegomanuel** [comment]
Hey @gabrieljaegerde thanks for your message!
As a first thought, I would create a new whole spreadsheet for each main Binance account (each one with its own API keys configured in the add-on) and have another _special_ spreadsheet that summarizes them all (using `IMPORTRANGE`, `QUERY`.. formulas) as an "overview" of all the accounts.

If I think in supporting multiple _main_ accounts in a single add-on installation, the main problem is the `418` responses (Binance temporarily banning us from issuing requests to the API) because of the increase in requests needed to be issued in order to keep each account updated.
That increase in the number of requests would be mainly affected by how many operations do you have/use in the spreadsheet.
If you only use `"orders/table"` and `"orders/done"` for example, it shouldn't be a problem if you have several accounts to check... eventually they will be all polled from the beginning and it will keep'em updated more easily afterwards (by just fetching new orders if the asset net balance was changed in the wallet).

I'm interested in your use case, mainly in how did you manage to sort out the `418` thing if you sync several accounts in a normal/average add-on usage. Remember that it should be "generic enough" to be usable by any user.
Maybe you just use a few `BINANCE()` operations or may be you adapted the code to be more specific to your case, so please describe a bit more how is your current add-on usage in the spreadsheet, that would help me to better understand the picture.
Feel free to create a PR or just keep talking here for further details, as you wish.

Thanks again! :beers:

**Comment by gabrieljaegerde** [comment]
Yes, the 418s are an issue. That is why I am working with buffer sheets. I have a trigger that checks the main sheets for issues every minute. If there are no issues, the contents are written to buffer sheets. If the main sheets are not loaded due to 418 errors then, the buffer will still have the last contents. In my dashboard I call on the buffer sheets then. Not the prettiest solution but it works for me.

**Comment by diegomanuel** [comment]
Hey again @gabrieljaegerde!

As I said, I would stay with the multiple spreadsheets option, having one as the "overview" spreadsheet.
It's the simpler and cleanest solution so far, because the added complexity for the add-on to keep it's "generic-enough-for-most-people-use-cases" approach will be too much to afford. The code changes would be massive to adapt all the operations and to keep working fine without too much `418` noise.
By having different spreadsheets, you spread API request into different google servers/instances/IPs, so it's always better to divide/decentralize in cases like this.

If you think that the changes you've done could be useful to other folks, feel free to continue your fork and take the updates you may need from mine, np at all.

Good luck with that and happy trading! :beers:
