### ISSUE TITLE
[BUG] Error: Request failed with status: 451 (line 1733).

### ISSUE THREAD

**Issue by Marcusskus** [diegomanuel/binance-to-google-sheets#158]
Hi there 

I hope this message finds you well. I've been encountering an issue with our GitHub codebase that I could use your expertise to resolve. A few days ago, everything was working fine, but since yesterday, I've been consistently seeing the following error:

```
Error: Request failed with status: 451 (line 1733).
```

I attempted to update the code from our GitHub repository, hoping it might resolve the issue, but it seems that the changes in the latest commit did not address the error, as I'm still encountering it on line 1733.

I would greatly appreciate your help in identifying the root cause of this issue and finding a solution to fix it. If you could take a look at your earliest convenience, it would be much appreciated.

Please let me know if you need any additional information or access to specific logs or files to diagnose the problem more effectively.

Thank you for your prompt attention to this matter.

**Comment by diegomanuel** [comment]
Hey @Marcusskus plz take a look at this issue: https://github.com/diegomanuel/binance-to-google-sheets/issues/142

It's due to Binance restrictions, not a problem with the add-on code itself.
You could try some workarounds mentioned in that issue, but the ultimate solution is to use a proxy like the one I've added here: https://github.com/diegomanuel/binance-to-google-sheets-proxy

Good luck, cheers!
