### ISSUE TITLE
Don't manage to get the orders

### ISSUE THREAD

**Issue by datadragon61** [diegomanuel/binance-to-google-sheets#17]
First of all, thanks for the great tool! Really saves a lot of time.

The issue is that I don't manage ot pull  the orders at all. 
All my orders are against BTC and USDT.

However, nothing is coming. I tried the following ways:

=BINANCE("orders/table", "BTC")
=BINANCE("orders/table", "USDT")
=BINANCE("orders/table")
=BINANCE("orders/table", "BTC", "USDT")
=BINANCE("orders/table", MySheet!A1:A3, "BTC")
=BINANCE("orders/table", MySheet!A1:A3)

What can be the reason?

Thanks!

**Comment by ziggetty** [comment]
hi, i had the same problems, but did resolve it.
due to my email correspondence with diego, he said it was due to a bug which was now resolved.

your last try =BINANCE("orders/table", MySheet!A1:A3) should be correct, when the traded coins 
against USDT are in MySheet!A1:A3
against BTC the following is i think correct =BINANCE("orders/table", MySheet!A1:A3,"ticker:BTC")

In the coding of the script is a check if assets has changed, and when nothing has changed there
is no fetch done for orders.

i think that is flawed, because:
- i am not sure about this one(so just maybe) when the first run of fetching orders goes wrong 
  but the assets are fetched then in the second run the assets are not changed and the fetch of
 orders is not done.
- when between 2 runs of fetch orders you have done a SELL and BUY of the same qty of 1 coin,
  your assets did not change (you have still the same number of coins) but there are new orders
  which then are not fetched because of this check.

I removed (remarked) this check from the code.

But first you can check what happened.

when in your sheet go to 'tools' 'script editor'
a new window will open
on the left site go to 'executions'
search for the last 'dotablespoll'
at right side click open
now you see all kind of info messages such as

Feb 25, 2021, 4:27:09 PM
Info
[BinDoOrdersTable] Processing sheet: Orders Table
Feb 25, 2021, 4:27:16 PM
Info
[BinDoOrdersTable][SPOT] Fetching orders for 'ADABUSD'..

and maybe also warnings as :  Skipping unchanged asset

if you find that one , you have the same problem i had.

you can then find "Skipping unchanged asset" in the script
remark the test and see if it solves your problem.

good luck ! 

Robert

**Comment by diegomanuel** [comment]
Hey folks thanks for reporting the issue.
It's already solved on `master` but the fix it will be included at `v0.4.2` release in a few more days.
Added support to `"unchanged: false"` option (as 3rd parameter for `"orders/table"` operation) to disable the unchanged assets verification, but I recommend to just disable it if you experience problems, but re-enable it later (by removing the option) as soon as you can.

Stay tuned, thanks again! :beers:
