### ISSUE TITLE
query in demo sheet misbehaves

### ISSUE THREAD

**Issue by ziggetty** [diegomanuel/binance-to-google-sheets#20]
hi Diego,

i will not call it a bug, but ....
if you query the order table it starts as follows =query('Orders Table'!$A$4:$J.....

in the beginning when orders table is empty and closed trades are coming in
probably sort of shift rows down happens and the $A$4 in the query also shifts down
and becomes for example $A$33 

maybe better to query $A:$J 
but then the condition "where B > 1"  picks up a row from the headers

or just mention it in a 'binance to google sheet for dummies' doc ;-)

**Comment by diegomanuel** [comment]
Hey @ziggetty you are right!
It only happens the first time when the orders table is empty (and it's not an add-on issue).
Anyways, that example is currently not needed anymore since the new `"orders/done"` operation works as much as the same, plus taking into account multiple `"orders/table"` sheets you may have and summarizing them into a single result list.
I've removed that sheet from demo spreadsheet.
Thanks for noticing this! :beers:
