### ISSUE TITLE
Error: Request failed with status: 418 (ligne 2599) - since yesterday Binance update

### ISSUE THREAD

**Issue by Christoth67** [diegomanuel/binance-to-google-sheets#24]
**Describe the bug**
Since yesterday Binance new release, the API seems not working anymore with the message 
Error: Request failed with status: 418 (ligne 2599). In GoogleSheet

**To Reproduce**
1. In a GoogleSheet in which this script was already properly working you can see that the formulas dont work anymore... To make a test just enter the formula : =binance("prices") in an empty sheet
2. press enter
3. after a short time with the loading message you will get the #error content in your cell
4. and you can see the error message

**Expected behavior**
I have been using this formula in this spreadsheet on a daily basis for weeks with no issues
Well, sometimes it does not work, but it always works if you refresh twice or 3 times
But now It definetely does not work at all even after a dozen tries

Is it linked to the Binance major update ?

Thanks

**Comment by diegomanuel** [comment]
Hey @Christoth67 thanks for reporting the issue!

I'm currently seeying a lot more `418`s but just on "prices" operation.
The other operations are working with an expected/acceptable amount of `418`.
Anyways, after several attempts (5 times/runs/minutes) the add-on was able to fetch new prices (I have `1m` configured for prices operation). It made 10 request attempts per run, so it took around 50 request to successfully fetch prices (in the meantime, the "fallback cache" returned the last `200` response that is kept for 1 hour).

It might be due to Binance updates but not sure.. nothing was changed in the code to affect this operation in that way.
By this time, you should have fresh prices data already in your spreadsheet, so I'm assuming that there is no issue, ergo closing this ticket.

If you keep experiencing problems, plz let me know by reopening it.
Thanks again! :beers:

**Comment by Christoth67** [comment]
Thanks

 

You are right. It seems better….

 

Thanks for your great API…

**Comment by crashnick16** [comment]
I believe this is happening due to the fact that the script is refreshing too often. upon receiving 429 it should wait for a particular period of time before retrying otherwise binance will ban it.

HTTP 403 return code is used when the WAF Limit (Web Application Firewall) has been violated.
HTTP 429 return code is used when breaking a request rate limit.
HTTP 418 return code is used when an IP has been auto-banned for continuing to send requests after receiving 429 codes.

**Comment by diegomanuel** [comment]
Yes you are right, although I never was able to see any `429` responses when developing and running the add-on myself.
In deed, the add-on code has the special case to take care of `429`s but as I said, I never got a 429 response so far.

This is the main reason of adding intervals configuration in the add-on's main menu, so the user can increase the intervals to its desired values, avoiding too much `418`s.. but unfortunately the code runs on Google servers from whose IP addresses are shared among any other users making requests from google products to Binance.
Any add-on (or other software) running on Google's servers making requests to Binance API counts as effective requests from same Google's servers IP and sadly we can't do anything about it  =/
We entirely depend on how many IP addresses are distributed amongst Google servers and the max request cap set by Binance for each IP.

Good luck! :beers:

**Comment by Christoth67** [comment]
By the way the auto update does not work with this formula :
= Binance(« prices »).  
Is it normal ?

Christophe

**Comment by diegomanuel** [comment]
It should work as it's currently working on the DEMO and many other places:
`=BINANCE("prices")`

Make sure to configure its update interval from the "Binance" main menu!
