### ISSUE TITLE
[BUG] excessive access to google account required

### ISSUE THREAD

**Issue by neillamontuk** [diegomanuel/binance-to-google-sheets#25]
**Describe the bug**
ALL OF THE FOLLOWING PERMISSIONS?
Some i can understand, but others seem like serious potential security risks. I do not think you need all of these permissions, and there is no way i will give them no matter how pleased I was to find your solution to my problem.

This app wants permission to:
_See your spreadsheets.._.        All of them in the google account
_Edit your spreadsheets..._       All of them in the google account
_Create new spreadsheets..._   All of them in the google account
_Upload or download your spreadsheets..._            Why would you need to download my spreadsheets?
_Organize and delete any of your spreadsheets..._  No need, not ok
_See and change the people you share spreadsheets with..._  not just my data but anyone who is shared on any of my spreadsheets

_There may be sensitive information in your spreadsheets, like financial records or personal lists._    Yes there might be

_Create a network connection to any external service (e.g., to read or write data)_    OK i want this to happen

_Allow this application to run when you are not present..._ for what possible reason?

_Display third-party web content in prompts and sidebars inside Google applications_   I guess you want your pop ups ok can live with this

_Run third-party code in your browser_  not sure of the implications of this, is it necessary?

_Receive data you input_    OK

**To Reproduce**
Use this code

**Expected behavior**
I expected to give the code/author access to this one spreadsheet, to connect to a network service, and insert data into this one spreadsheet.  Anything beyond this seems like a data mining operation and a security risk.

I was very happy to find your code, and pleased I managed to get it working in my spreadsheet, but then I read all of the authorizations required and I had to delete it.  Please narrow these required permissions down to only what is truly necessary! i can not give you full control over every spreadsheet in my google drive!

Neil

**Comment by diegomanuel** [comment]
Hey @neillamontuk that's very weird, it shouldn't ask you for any "controversial" permission, but just that ones:
- View and manage spreadsheets that this application **has been installed in**.
So NO access to any other documents, just the current spreadsheet in where is running.
- Connect to an external service.
Of course, needed to request the Binance API.
- Allow this application to run when you are not present.
Those are triggers that keep the data updated in the background, allowing the formula results to be automatically updated on the spreadsheet.

It should look like this here: https://myaccount.google.com/u/0/permissions
![image](https://user-images.githubusercontent.com/5076158/110553756-3eef4b00-8118-11eb-93e1-7bac3964959e.png)

**If that's not your case, then you are using another code, so be careful.**
And besides, you can always see the code and audit it, since it's a public repo.

Good luck, cheers! :beers:

**Comment by neillamontuk** [comment]
Thank you for the reply, the permissions are shown below...
[image: image.png]
I copied the code directly from your github, so I am not sure why the
permissions could be different.
I have searched through the code to see if there is anything obviously
suspicious, but I have very little coding knowledge, so I may not notice
anything dangerous if it was there, but just receiving your detailed reply
helps me to relax a little.
I have now decided to keep using the code (there is nothing too
sensitive in this account anyway) so thank you for sharing your work, it is
really cool to see the data updating automatically, especially while the
prices are going in the right direction!

Neil
