### ISSUE TITLE
[BUG] orders/done and orders/table doesn't work

### ISSUE THREAD

**Issue by sluzhynskyi** [diegomanuel/binance-to-google-sheets#27]
Works with formula "=Balance("orders/open")" but doesn't work with table and orders done (bcs done requires orders/table)

![image](https://user-images.githubusercontent.com/44615981/110541766-de203c80-8130-11eb-9ef7-293a7acba4db.png)

**Comment by diegomanuel** [comment]
Hey @sluzhynskyi that's not a but, the problem is that you set "USDT" as 2nd parameter (and it should be the 3rd one, but as "USDT" is already the default, you don't need to specify it).
You need/must pass the assets/symbols to fetch orders from in the 2nd parameter, take a look to the readme section:
https://github.com/diegomanuel/binance-to-google-sheets#operation-orderstable-private

You may pass'em in form of "full pairs", like: `=BINANCE("orders/table", "BTCBUSD, ETHBTC", "ticker: range")`.
Good luck, cheers! :beers:

**Comment by sluzhynskyi** [comment]
but still doesn't work, even with your example(
![image](https://user-images.githubusercontent.com/44615981/110803663-18502200-8288-11eb-8038-c7d500ea5fc1.png)
![image](https://user-images.githubusercontent.com/44615981/110803777-39187780-8288-11eb-9d0a-3260b258b49f.png)

**Comment by diegomanuel** [comment]
Hey @sluzhynskyi other user reported a similar issue but when he tried in a new blank spreadsheet, it worked just fine.
I can only think in something wrong when you copy/pasted the code from github into your spreadsheet's code console.

Make sure to not have any leftover there, copy the whole contents from the latest release and paste it again:
https://github.com/diegomanuel/binance-to-google-sheets/releases/download/v0.4.1/BINANCE.gs
NOTE: There are some fixes/improves at master branch that weren't released yet.
