### ISSUE TITLE
[BUG] Not accepting authorization

### ISSUE THREAD

**Issue by sebastianm23** [diegomanuel/binance-to-google-sheets#3]
The tool should normally authorize via "Binance > Authorize add-on!". Having this steps done and after refreshing it still shows the pop up in the right corner. There is also no setting available for setting up the API key since the tool acts like it's not authorized. 

In Google the App shows up as Third Party Authorized App.

**Comment by solcomart** [comment]
Same issue with 0.3.0 version.
0.2.0 works fine

**Comment by diegomanuel** [comment]
Hey folks, thanks for letting me know the issue! :clap: 
I've made some adjustments to the flow and it should work as expected now, plz let me know and re-open if needed!
**Re-released `v0.3.0` with the fix.**

Sadly, we can't detect from whitin the code when the user authorizes the add-on since there is NO `onAuthorize` trigger or something like that (basically a mechanism to let the code know when it gets authorized).
The `onInstall` trigger only works when the add-on is installed from the Google Marketplace, but this is not our case (and besides, marketplace add-ons can't have triggers smaller than 1 hour.. so totally discarded).

To be honest, the Google platform to run the code at our spreadsheets is pretty shitty.. but we can't do anything about it.  =/
