### ISSUE TITLE
[BUG] Request failed with status: 418

### ISSUE THREAD

**Issue by datadragon61** [diegomanuel/binance-to-google-sheets#33]
Very often this error appears.
Sometimes reloading helps, sometimes doesn't.

A good tool in concept, but in reality I spent more time dealing with errors than actually using it.

**Comment by diegomanuel** [comment]
Hey @datadragon61 you may need to decrease the update intervals for your operations.
Error code `418` means that Binance is rejecting request because it's receiving too many from the Google's server in where the add-on code is running for your spreadsheet (and it's totally outside of our scope).
Try to "spread" different operations in different intervals.
It can't guarantee to always work because of the 418's.. but it should help.

Reloading the spreadsheet will make no difference, don't waste your time, we can't avoid 418's from Binance.
Make sure also to have the latest release running in your spreadsheet.

Good luck! :beers:

**Comment by datadragon61** [comment]
I don't have auto refresh turned on at all. That's not the issue.

Both me and my friend experience the same. Sometimes it just doesn't work..

Anyway, we stopped using it, so it's not that important anymore.

Thanks for the support.
