### ISSUE TITLE
order/table fetching bug

### ISSUE THREAD

**Issue by dr1361teh** [diegomanuel/binance-to-google-sheets#37]
Orders do not fetch from Binance completely ! So, we can not have a reliable gain and loss report .
I use this command :   =BINANCE("orders/table", Dashboard!$A10:$A)

**Comment by diegomanuel** [comment]
Hey @dr1361teh could you give more information about the problem? Like:
* Market (spot, cross, isolated, futures?)
* Pair/s experiencing the problem.
* Logs from Google's developers console for "orders/table" operation (doTablesPoll).
* Any other information that could help to find the bug.

Thanks for the report!

**Comment by dr1361teh** [comment]
Thanks for your kind consideration,

FYI, I duplicate and use your demo google sheet which is v0.5.0

1- The market is Spot
2- I exported the excel file of 3 months "Trade History" from Binance which has 353 records. But in the order/table sheet, I can find just 206 records. so it seems 147 records are missed !
3- One side of my all trades is USDT.
3- I need your assist to find the logs. I couldn't find them !
4- =BINANCE("account", "spot") and =BINANCE("orders/open") works fine ! And the information is updated properly. 

In addition, every time I create a new Google sheet from your DEMO (with similar assets in DASHBOARD), part of my orders are shown in the table/order ! Unfortunately, they are not the same!

Thanks.

**Comment by diegomanuel** [comment]
Damn I'm really puzzled with this one! Try the following:

1. Pick a problematic pair that has missing orders, like **BTCUSDT**.
2. Create a new blank sheet inside one of your current spreadsheets with the add-on on it.
3. Set at **A1** in there: `=BINANCE("orders/table", "BTCUSDT", "ticker: range, unchanged: false")` (change `BTCUSDT` to the pair selected at `1.`)
4. If there are missing trades, try to add another problematic pair to the 2nd parameter, like: `"BTCUSDT, ETHUSDT"` and see if they start to "miss-out" from a specific date. Is there any "pattern" that you could identify between both problematic pairs?

It should work just fine in a new blank sheet and using `unchanged: false` since the operation will always try to fetch new orders no matter if the asset balance was changed or not.

Good luck with that and let me know how it was!

**Comment by dr1361teh** [comment]
Thanks for your assist.

Your suggested command works fine and pairs are fetched in the new sheet but not added to the "Order / Table" sheet.

FYI, I changed the command of "order/done" sheet to =BINANCER("orders/done", "", "max: false"). Because in the dashboard, the "Total Buy / Sell" columns require all trade records.

There seems to be a problem with the "order / table" updating that needs to be addressed.

Additionally, I added a new sheet with "=BINANCER("account", "spot")" command, and I use this sheet for source of Holdings Column in Dashboard. This can show us the actual amount of assets. . Because, your formula do not consider commission. So you can use this suggestion in your demo sheet.

It would be appreciated, if you could suggest me a formula that shows me the amount of payment for my existing assets.

Also, I ask you a new feature to show us the commission value in a stable currency such as USDT. This may be a complex feature, but it is very valuable.

BTW, Thanks for your kind efforts.

**Comment by dr1361teh** [comment]
Hello Diego,

I received a new error for "doTablesPoll" from yesterday:
**Error: Got 401 from Binance API! The keys aren't set or they are not valid anymore.**
I re-created the API key from Binance several times and set it up on the Google sheet, but the problem persists :(
Also, recopying the sheet can not solve the problem ! 
Any solution ?

**Comment by dr1361teh** [comment]
Other error ! :((((  IP banned :((((

Error: Request failed with status: 418

**Comment by diegomanuel** [comment]
Hey @dr1361teh not sure what more to tell, it should work, sorry about that!
