### ISSUE TITLE
[BUG] Exception: Service invoked too many times for one day: urlfetch. (line 2818).

### ISSUE THREAD

**Issue by fuimaranwe** [diegomanuel/binance-to-google-sheets#39]
Hi Diego, great script. Ellerine sağlık (health to your hands) as we say in Turkey :)
I have been using your script in a couple of sheets but in one of them I started to see "Exception: Service invoked too many times for one day: urlfetch. (line 2818)." error. Other sheets are working just fine but this one sheet started to give this error last night.
Thanks in advance

**Comment by diegomanuel** [comment]
Hey @fuimaranwe thanks!

That's due to the add-on making too much requests (calls to `urlfetch` function to fetch data from Binance API) and it's a limitation on the Google's side (this time, Binance has nothing to do with it). It will be automatically cleared after a while (may be a few hours). The total `urlfetch` usage quote seems to be refreshed once per hour.

It may happened because of too much request/fail/retry attempts, try to increase a little bit the update intervals for some operations.
Good luck, cheers! :beers:
