### ISSUE TITLE
[BUG] API not being correctly retrieved

### ISSUE THREAD

**Issue by hAislt** [diegomanuel/binance-to-google-sheets#44]
Hello,

thanks for your contribution.
I have set up the addon and with and some operations work but some don't.

=BINANCE("version") works.
=BINANCE("last_update") works.
=BINANCE("prices") works too.
but some don't work and I don't know why could you please explain?
Not working:
=BINANCE("history", "BTCUSDT", "interval: 1h, limit: 24")
=BINANCE("stats/24h", A1:A3)

I also setup my Binance API but no given command is working.
Output is. Error: Got 401 from Binance API! The keys aren't set or they are not valid anymore. (Line 2843).

But API is working and should be able to access (read permission).
Much thanks in advance.

**Comment by jurgen2005** [comment]
on the history command I get : 
Error: Request failed with status: 418 (regel 2870).
=BINANCE("history"; "BTC"; "interval: 1h, limit: 24")

**Comment by ziggetty** [comment]
i also got 401 errors the last few days, and later it worked again.
so maybe binance had problems ??

**Comment by ziggetty** [comment]
> 
> 
> on the history command I get :
> Error: Request failed with status: 418 (regel 2870).
> =BINANCE("history"; "BTC"; "interval: 1h, limit: 24")

errors 418 we all get on several functions, just because the requests to the api are sent from the shared google IP's from where google sheets run. unfortunately we have to live with it.

**Comment by diegomanuel** [comment]
Hello @hAislt and folks!
The `418` problem is exactly as @ziggetty described above, @jurgen2005.
But regarding the `401` one, is still happening @hAislt?

Those 2 don't require any API key, so they should work (but they could fail because the `418` problem).
```
=BINANCE("history", "BTCUSDT", "interval: 1h, limit: 24")
=BINANCE("stats/24h", A1:A3)
```

Try to disable the futures and/or the cross/isolated wallets if you don't use them.
At least the futures one, has its own checkbox to be enabled when creating the API key from Binance site.

Reopen the issue if the problem is still there, good luck!
