### ISSUE TITLE
[FEATURE] Add more columns to =BINANCE("prices")

### ISSUE THREAD

**Issue by cristipurdel** [diegomanuel/binance-to-google-sheets#48]
**Is your feature request related to a problem? Please describe.**
It would be nice to have also ATH, Last 52w high/low, Last 24h high/low

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
If not possible, then add separate option for e.g.: "ATH", "52w_high", "24h_low", etc.

**Additional context**
Not sure if binance api does support it, but it would be nice to have

**Comment by ziggetty** [comment]
it helps to get acquainted with the binance api. although the api documentation is not an easy read.
most api calls deliver basic info on a request, so you have to combine requests.
for example https://api.binance.com/api/v3/ticker/price  only delivers prices for the tickers.
many things could also be acomplished just in the google sheet without doing a request to the api.

nice would be to have for example name(bitcoin, cardano etc.) of the coin next to the ticker.
but that could also come from a lookup in a static table on another tab
so instead of 
![afbeelding](https://user-images.githubusercontent.com/79652361/114473874-5cbb3e80-9bf5-11eb-89e9-b59dbd3662cf.png)
i could between colums D & E have a column with the name
which i could get from another tabpage with static info and
just do a lookup with the value of the value in column D
