### ISSUE TITLE
[FEATURE] Error instead of question mark when ticker isn't found

### ISSUE THREAD

**Issue by Vozf** [diegomanuel/binance-to-google-sheets#50]
Now `?` is displayed for nonexistent ticker but error seems more suitable which allows handling with `IFERROR`

**Comment by diegomanuel** [comment]
The only way to report a real error (to be catched with IFERROR) from the code to the UI is to reject the whole operation.
This penalizes too much when only one pair is non existent from a big list, and makes no sense to reject the whole list because one missing/bad pair.
I suggest you to use an IF to detect the "?" if needed.
