### ISSUE TITLE
[FEATURE] Cache policy

### ISSUE THREAD

**Issue by Vozf** [diegomanuel/binance-to-google-sheets#51]
cryptofinance has cache which allows running the cells over and over without addional api calls, and it slows down the page significantly without the cache in the current state

**Comment by ziggetty** [comment]
just my 2 cents:
- cryptofinance is not totally free ; but he has written some usefull 'best practices' comments.
- for reasons of limiting the number of api calls, i trigger the =binance functions only manual
  (but can imagine that traders who run a bot, let triggers run)
- i for example get all prices in one go "=BINANCE("prices",,"headers:false",Account!H1&A1)" 
  and trigger with a checkbox in cell Account!H1 or A1
  and where price needed i do a lookup in the other tabpage.
- with all triggers in the OFF state they also do not run when the sheet is closed.
- 
![afbeelding](https://user-images.githubusercontent.com/79652361/114619579-027cb500-9cab-11eb-88ee-0bd581e79dd6.png)

- diego also coded cache and does test to prevent not needed API Calls.
- we get errors (418's etc.) because all API calls to binance which are coming from a shared google IP
  are seen as if they are coming from 1 user. not much we can do for that.

I think diego does everything which is possible to prevent api calls.
on the other hand, we as end users should also minimize the number of '=binance' calls.
it is quite easy to code an =binance call to get the current price of every account line, where 
a lookup to another page is maybe a better solution.

a cache can also be a burden, when you need the info from the api call and because of error on the api
call you get back the 'old' cached info.

and further waiting for the opinion of diego ;-)

around the 5th of april i had an error rate in the 20% which made it almost not workable.
the last few days it improved
![afbeelding](https://user-images.githubusercontent.com/79652361/114618050-32c35400-9ca9-11eb-87b7-9fdaa71e4e46.png)
but still a 2% errors(avg 6% but declining) on the api calls (mostly 418's)

**Comment by fabiob** [comment]
Check my PR #53, it reduced my 418's to zero.

**Comment by Vozf** [comment]
My main concern is constant cell reloading with `Loading` label instead of value and not 418 so api cluster distribution doesn't solve this problem

**Comment by ziggetty** [comment]
> 
> 
> Check my PR #53, it reduced my 418's to zero.

thanks !

**Comment by diegomanuel** [comment]
Hey @Vozf the add-on uses cache to minimize API calls but it first try and re-try to fetch fresh data before taking it from cache (that's why you may see long "Loading.." messages while the add-on is trying to fetch).
The PR that @fabiob proposed may alleviate your situation, it's already merged on `master` and it will be included in the next release. Manually update your code or you may need to wait for the next release!

Good luck and thanks once gain to @fabiob!
