### ISSUE TITLE
[BUG] Historic function - Problem when time is specified

### ISSUE THREAD

**Issue by djo4u** [diegomanuel/binance-to-google-sheets#58]
**Describe the bug**
When i use binance("history", xxx) and i specified Date + **Time**, the time is not correctly parse as an option

**To Reproduce**
For example, my usecase:
=BINANCE("history", "EURUSDT", "interval: 5m, start: 2021-02-10 10:32:00, limit: 500")

**Expected behavior**
The first line result is:  "2021-02-10 01:00:00". 
I think it could be: "2021-02-10 10:35:00"

I think the problem come from the "parseOptions(opts_or_value)" function.

**Screenshots**
On debug, the log :
![image](https://user-images.githubusercontent.com/79139852/115399401-7279c680-a1e8-11eb-92b9-42bb496ba419.png)

Bug Result :
![image](https://user-images.githubusercontent.com/79139852/115399664-bc62ac80-a1e8-11eb-9375-d3be0fd3b49a.png)

**Additional context**

**Comment by diegomanuel** [comment]
Hey @djo4u thanks for the report!
I pushed the fix but it's on `master` for now, it will be available on next release.
If you update your code, you only need to change the formula from: `... start: 2021-02-10 10:32:00, ...`
To: `... start: 2021-02-10-10-32-00, ...` (using "-" instead of ":" and the blank space between date and time).

Stay tuned, good luck! :beers:
