### ISSUE TITLE
Integration of EUR

### ISSUE THREAD

**Issue by mchurlet** [diegomanuel/binance-to-google-sheets#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Integration of the EUR in the list of fiats and possibility to display the prices in euro.

**Additional context**
You have done an incredibly useful job. Thank you
![Clipboard01](https://user-images.githubusercontent.com/8840295/105226888-7d28af00-5b58-11eb-9714-877687620627.jpg)
![Clipboard01](https://user-images.githubusercontent.com/8840295/105227222-f32d1600-5b58-11eb-84b1-90eb1fc3d2f4.jpg)

**Comment by diegomanuel** [comment]
Hello there, thank you!
That combobox for "Ticker" wasn't really used in the DEMO spreadsheet (I just changed it to be used as example).
If you want to use EUR instead of USDT, you can use:
`=BINANCE("prices", A10:A, "EUR")` directly or `=BINANCE("prices", A10:A, B10)` if you add "EUR" to the options at `B10`.
`=BINANCE("prices", A10:A, "ticker: EUR, prices: true")` to get only the prices (as it is in the DEMO).
`=BINANCE("prices", A10:A, "ticker: "&B10&", prices: true")` if you add "EUR" to the options at `B10`.

Hope that helps with what you need, good luck!
