### ISSUE TITLE
[FEATURE] Historical Data/24h Stats/Account Info frozen at 1 min, add refresh trigger as user defined (default at 10m)

### ISSUE THREAD

**Issue by cristipurdel** [diegomanuel/binance-to-google-sheets#61]
**Describe the bug**
Cannot modify them to other values

**To Reproduce**

**Expected behavior**
Should work like the other 3 options

**Screenshots**
![image](https://user-images.githubusercontent.com/41154308/115691083-ff925c00-a35d-11eb-9aec-48e3964956ed.png)

**Additional context**

**Comment by diegomanuel** [comment]
This happens when the operation fails to run and it's automatically re-schedulled to be run in the next minute, no matter the time interval configured (even being disabled).
Scenario:
* I have turned OFF the interval for "prices" operation at add-on config, so NO auto-refresh for it.
* I add a formula in my spreadsheet with `=BINANCE("prices", "..")` and it fails to load (418 or whatever).
* The add-on will try to get a value in the next minute (so if you take a look in the main menu like in your screenshot, you will see "1m" instead of the expected "off" value).
* This error-retry cycle could happen many times, but once the prices are fetched and the operation finishes, it will be back to the original state: "off".

May be I should do an exception in the case of "off" value! :thinking:
