### ISSUE TITLE
[FEATURE] Pause a orders/table sheet

### ISSUE THREAD

**Issue by niesteszeck** [diegomanuel/binance-to-google-sheets#65]
**Is your feature request related to a problem? Please describe.**
related to #54, specially to the process detailed in my [comment](https://github.com/diegomanuel/binance-to-google-sheets/issues/54#issuecomment-826350411) 

**Describe the solution you'd like**
I want to disable/pause a `=BINANCER("orders/table")` (for example, deleting it or putting some char at the beginning like: `a=BINANCER("orders/table"`).

**Describe alternatives you've considered**
A menu for doing this, but I prefer to add a char at the beginning of the cell formula

**Additional context**
I want to do this to reduce the number of active orders/table sheets for optimizing the retrieve of the pending ones

**Comment by ziggetty** [comment]
related to #43 

your prefered solution is possible.

i mostly change it to let it look just to 1 pair instead of all traded pairs
but i can do that because i do not have many orders.

i prefer an option in the menu.

in general i don't like the triggers, becasue they also keep running when you have closed your google sheet.
and we dont want calls to the API when not needed, to prevent 403/418 errors.
don't know if there is an option to NOT let triggers run in background (cq when google sheet is not open)

**Comment by niesteszeck** [comment]
Oh!!! 

So if I put the formula again, it will resume? This is a good notice.

**Comment by ziggetty** [comment]
in my opinion yes.
i have a sheet with traded pairs
and i amend the formula =BINANCER("orders/table",'Traded Coins'!C25)
only to my last traded pair.

but i have had in the beginning also some missing trades due to (i think a bug diego solved)
and although there is a message to NOT add/alter the data by hand in the orders table
at some point i deleted all records in the orders table table, and started fresh
took a night (becasue all those 403/418 errors we can not prevent), but after that all ok.
so in my opinion do not mess with the data in the orders/table tab, or delete ALL and start fresh

i try not to look to much on that sheet.
in another sheet i query the orders/table
![afbeelding](https://user-images.githubusercontent.com/79652361/116622263-b38a7d00-a944-11eb-8fdc-c1ac51563a8e.png)
in column A to J the data from the query
in column L and further my own calculations, where i try to calculate avg buy price (which are later added to my acct tab)  
and profit %.
![afbeelding](https://user-images.githubusercontent.com/79652361/116622543-2ac01100-a945-11eb-89ed-399968abea7f.png)

its still a work in progress and there are still bugs in my sheet (thinking faults and new situations which breaks my sheet)

**Comment by diegomanuel** [comment]
Hey @niesteszeck just follow the @ziggetty advice for now :ok_hand: 
Operations will resume as soon as you set back the formula again.
Anyways, I'll push code changes to disable/pause the orders/table operation (at #43).
