### ISSUE TITLE
Convert USD to Local Currency

### ISSUE THREAD

**Issue by TwinninG** [diegomanuel/binance-to-google-sheets#66]
Would it be possible to change the currency to other currency? It might be helpful for some of us. Thank you! :)

**Comment by ziggetty** [comment]
i think you can easily do that on the frontend (cq google sheet)
you can get for example the EURUSDT price and do the calculation
i have my account lines in USDT and in another column in EURO
in the same way it can be done for other fiat currencies or BTC

**Comment by TwinninG** [comment]
Thanks a lot! That is very helpful! :)

But would it be possible to change the currency to PHP in the entire sheet? I don't have much knowledge about the codes. I find it easier for me to use my local currency rather using USD EUR etc. 

![image](https://user-images.githubusercontent.com/29818697/116770410-660e2d00-aa76-11eb-8447-57f7830b800e.png)

Thank you so much!

**Comment by ziggetty** [comment]
i dont think binance has an exchange price for PHP (phillipine peso)
but you can get the following
![afbeelding](https://user-images.githubusercontent.com/79652361/116774201-4c132100-aa5b-11eb-8b88-a3304748031c.png)
by having in a cell (in the example C15) you can calculate the values in PHP
instead of manual entering the exchange rate you can use the googlefinance function.
formula in C15 :  =GOOGLEFINANCE("CURRENCY:"&A15&B15)

**Comment by diegomanuel** [comment]
Great @ziggetty exactly that, thanks!
Do what he says, @TwinninG you only need to convert to your local currency using `GOOGLEFINANCE` function.
