### ISSUE TITLE
[BUG] Enter a descriptive title here

### ISSUE THREAD

**Issue by pruthviraj1991** [diegomanuel/binance-to-google-sheets#7]
**Describe the bug**
Getting following error for `Done from Orders Table` 
`Got 400 from Binance API! The request seems to be wrong`

**To Reproduce**
used formula `=BINANCER("orders/done", Dashboard!$A10:$A)`

**Expected behavior**
Should load the done orders from my trades. Api key is working well for open orders
<img width="686" alt="Screen Shot 2021-02-05 at 3 10 30 PM" src="https://user-images.githubusercontent.com/1300896/107017259-e816ee80-67c4-11eb-8af0-fe4109ea09e3.png">

**Screenshots**
attached
<img width="686" alt="Screen Shot 2021-02-05 at 3 10 30 PM" src="https://user-images.githubusercontent.com/1300896/107017333-fe24af00-67c4-11eb-9d9b-24035151b3c7.png">

**Additional context**

**Comment by diegomanuel** [comment]
Hey @pruthviraj1991! :wave: 
This seems to be a problem with the data you may have at cells `Dashboard!$A10:$A`.

Note that cells at `Dashboard!$A10:$A` should have simple symbol names (like `BTC`, `ETH`) and NOT pairs (like `BTCUSDT`, `ETHUSDT`) and if any of those `$A10:$A` cells have and invalid symbol it will fail (more accurately, if the pair `symbol+USDT` doesn't exist at Binance).
The formula `=BINANCE("orders/done", Dashboard!$A10:$A)` will fetch given symbols against the `USDT` pair by default.
You may specify another pair like: `=BINANCE("orders/done", Dashboard!$A10:$A, "BNB")` **BUT** note that ALL pairs must exist on Binance (ie: "BTCBNB", "ETHBNB") or it will fail as it's happening to you.

Review and try, and if you are still having problems, paste the data or take a screenshot with the cell values for `Dashboard!$A10:$A`.
Hope it helped, good luck!

**Comment by pruthviraj1991** [comment]
Actually, I have only symbols like BTC, ETH only in them but still, the issue happens. Am I missing something?

Btw its really great tool to integrate into sheets. Thanking you for developing this

**Comment by diegomanuel** [comment]
Thank you @pruthviraj1991!
I can see several symbols there and in order to work with `=BINANCE("orders/done", Dashboard!$A10:$A)` you must be sure that ALL pairs (each symbol+"USDT") from that range exists on Binance SPOT: `BTCUSDT`, `BCHUSDT` ... `KMDUSDT` ... and so on.
If at least ONE of them doesn't exist, it will fail entirely! (and that's wrong from the add-on side)

I will make a change/fix to not fail entirely if some of the range pairs doesn't exist, but it will be ready in the next release: `v0.4.0`.
In the meantime, you could try to reduce the range by discarding some symbols, like:
`=BINANCE("orders/done", query(Dashboard!$A10:$A, "select A where A<>'MTL' and A<>'ONT'"))`
You can keep adding **exclusions** by adding more `and A<>'symbol'` in there.
Or instead of **excluding**, you may do it by **including** symbols:
`"select A where A='BTC' or A='ETH'"`
You can keep adding **inclusions** by adding more `or A='symbol'` in there.

Be ready to `v0.4.0`, it will come with several fixes/improves!
Good luck with that, cheers! 🍻

**Comment by pruthviraj1991** [comment]
Thanks for reply @diegomanuel 

All the symbols in the above list are traded with USDT pair, I have tried the above query but wasn't working. Am not sure if some of them are restricted in certain countries but I could place an order in Binance app for all the above pairs.

Thanks a lot would be waiting for v0.4.0

**Comment by diegomanuel** [comment]
@pruthviraj1991 I think `v0.4.0` will make a difference here, but in the meantime try this:
`=BINANCE("orders/done", "BTC")`
If you have some fulfilled orders in **BTCUSDT** it should display your last 10 orders by default.
If that works for you, then the problem is in the `$A10:$A` range!
**NOTE:** You could manually test each pair and try to find out the conflictive one.
