### ISSUE TITLE
Exception: Service invoked too many times for one day: urlfetch. (line 89).

### ISSUE THREAD

**Issue by BenTenCrypto** [diegomanuel/binance-to-google-sheets#72]
Hello DiegoManuel,

First of all I would like to thank you for your magnificent tool, it is very beautifully designed and works very well.

To give you all the information that led me to this bug:
I have created a copy of your DEMO sheet, which plenty enough of functionalities for the use I have of it. 
Although, I trade with many different pairs (approx 20/25) which each can have an associated ticker to it, which can vary from pair to pair. 
Thus, i wanted to create an Orders/Table for each of the ticker I use for my trades (USDT, BUSD, BTC, BNB).
Before creating these tables everything worked just fine when i had the first one (USDT). (Although it didn't quite take all my historical data, but this is another issue which is minor to me).

I have come across a drawback which prevents me from using the spreadsheet properly: 
Exception: Service invoked too many times for one day: urlfetch. (line 89).

I have already come across several issues about this problem, and took your advice of increasing the Update Intervals from the Binance menu. Although when i try to increase the Prices refresh rate, it works fine (increase to 15 min) but when i try to increase another parameter (24h stats for example, to 15 min as well to relieve the request rate as much as possible) it resets completely all the parameters back to the Default setting. Thus, the "Service invoked too many times" keeps appearing (even when the price refresh rate is increased alone to 15 min)

Is there another way to increase the refresh rate manually in the code? Or would it be to time-consuming for me which doesn't know much about coding?
If you have any other idea where the issue could come from please feel free to propose anything, and I'll apply the changes to see the result.

Anyways thanks again for the amazing spreadsheet! If it doesn't work again I'll content myself with just the USDT ticker orders table.

**Comment by diegomanuel** [comment]
Hey @BenTenCrypto thanks for your kind words.
As @ziggetty suggested, you can manually update the formulas.
The urlfetch invocation problem happens when many API calls fails (`403` responses or whatever) and they are retried in the next minute. That causes to surpass the invocation limit for `urlfetch` set by Google's platform.

Two things to consider:
1) When you have configured an interval (ie 15m) but the operation fails (no matter the reason) it's re-scheduled to be run in the next minute (that's why you could see "1m" in the menu options) but that should be temporal. As soon as it gets a right response, the schedule time is set back to the configured value.
2) The latest release `0.5.1` has an improved API fetching mechanism, it should mitigate a lot the urlfetch invocation problem.

Try the latests version and good luck!
