### ISSUE TITLE
[FEATURE] orders/table to sort with newest at top

### ISSUE THREAD

**Issue by Mikelnz** [diegomanuel/binance-to-google-sheets#73]
Is there away the tables could populate with newest info at top (newest day at top)
This way referencing new activities from a table sheet to another sheet would stay in a consistent cell

**Comment by ziggetty** [comment]
i kept my orders table as it is, and did in another tab a query with sort .
=query('Orders Table'!$A$4:$J, "select A, B, C, D, E, F, G, H, I, J WHERE B > 1 ORDER BY D DESC ,C DESC, A DESC", 0)

i sort by pair and then on date, because in own columns i calculate profit/loss %
but you can change the sort order to date/time column C  trade-id column A

not all want the orders/table in the same way, so i think best is to set up an intermediate tab with query

**Comment by Mikelnz** [comment]
Nice.. thanks mate!

**Comment by diegomanuel** [comment]
Exactly as @ziggetty suggested, thanks dude!
