### ISSUE TITLE
[FEATURE] Remove de "loading" everytime it refreshs

### ISSUE THREAD

**Issue by hugoleosp** [diegomanuel/binance-to-google-sheets#74]
I started to use Google Sheets with this Binance API but every minute (or another interval) the whole table goes to "N/A" due to a "loading" updated data from Binance API Server.

I was using API Connector + CoinMarketCap but their refresh rate on the free package is 1h, but at least it doesn't change the values of the table until it has the new values avoiding breaking the other tables that are relied on them for the time taken with the refresh.

Binance takes sometime 5-10 seconds plus a bunch of errors to retrieve, and until it successfully refresh, the whole data based on this values get N/A.

My suggestion is to do just like API Conector + CMC does, it keeps the data table intact until it successfully retrieve updated data (you could leave at least an option to the user, and/or the user could get a function with the last update.

Thank you so much for the hard work =D

**Comment by diegomanuel** [comment]
Hey @hugoleosp I couldn't find a way to avoid that annoying "Loading.." message since it's something that Google platform does by itself every time an `urlfetch` is running.
So far, the only way to mitigate that is to use `IMPORTRANGE` within the same spreadsheet.
Example: I have prices in a hidden column and other visible with importrange and that does the trick 95% of times.

Good luck, cheers! :beers:
