### ISSUE TITLE
[BUG] Enter a descriptive title here

### ISSUE THREAD

**Issue by fbradyirl** [diegomanuel/binance-to-google-sheets#75]
**Describe the bug**
Wondering if we can get a new release? Issue from #47 is happening with the latest release from March. 

`=BINANCE("account", "spot")` is working fine, but 

`=BINANCE("account")` is not. (401 error with read access on my API key).

Someone mentioned enable Futures on the key but I dont see that option.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/254309/118101281-558f7800-b3cf-11eb-84ab-39b3d9070473.png">

**Comment by diegomanuel** [comment]
Hey @fbradyirl I can bet that is due to Futures being disabled on your Binance account.
The option appears once you enable it but you need to generate a new API key (since the old/original one, previous to enabling Futures doesn't work, as Binance itself said somewhere that I can't remember).

The previous release had futures wallet enabled by default (my mistake :sweat_smile:) but the latest one `0.5.1` is disabled by default.
My recommendation is: Update to the latest release and/or if you don't plan to use futures and/or margin, just disable them from the Binance main menu.

Good luck, cheers! :beers:

**Comment by fbradyirl** [comment]
I was able to build using my own fork without a new API key. All good thanks.
