### ISSUE TITLE
Exception: Service invoked too many times for one day: urlfetch. (line 1352).

### ISSUE THREAD

**Issue by davagnina** [diegomanuel/binance-to-google-sheets#8]
Hi!
I've found this code some days ago. I added it to my spreadsheet, and the first day works fine.
After that every time I open the spreadsheet I find this where the formula is placed:
Exception: Service invoked too many times for one day: urlfetch. (line 1352).

I tried to remove the "Run on change and every minute" setting from "Spreadsheet settings" but nothing changed.
I think the API call are not unlimited but I can not a number, to build the sheet on a right number of refreshes...

Anyway good job, it's very useful!

**Comment by diegomanuel** [comment]
Hey @davagnina, thanks!
It seems you've reached the **GoogleApps** limit for `urlfetch` calls (in fact, the add-on making calls to Binance API).
That shouldn't be a problem in a "well-designed" spreadsheet because that limit should be far away from the actual average add-on usage, **_unless_** you have something weird/wrong in your spreadsheet (aka, not using the add-on in an "optimal" way).

As first step, try to adjust (increase) the update intervals you may have configured from the `Binance->Update Intervals` main's menu item. You may better "spread the workload" by setting different intervals for different operations.

If you need further assistance, please reopen this issue and copy/paste here all the `=BINANCE()` functions you are currently using in your spreadsheet!
In that way, I can get a clear picture of how are you trying to use the add-on in the whole spreadsheet.

Good luck, cheers! :beers:
